name: CI Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
	  if: ${{ github.event.workflow_run.conclusion == 'success' }}
	  steps:
        - run: echo "I Succeeded, Have a nice Day";
  on-failure:
	runs-on: ubuntu-latest
	if: ${{ github.event.workflow_run.conclusion == 'failure' }}
	steps:
      - run: echo "I Failed, Boo Hoo";