# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        branches: [devbranch]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setting credentials
    - name: Set Credentials
      run: |
         git config --global user.email "woodsba@insercorp.com"
         git config --global user.name "Benjamin Woods"
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git fetch origin --unshallow
        git checkout ${{ matrix.branches }}
        git pull origin ${{ matrix.branches }}
        git pull origin master
        git push origin ${{ matrix.branches }}
