# This is a basic workflow to help you get started with Actions

name: CITest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ devbranch ]
  pull_request:
    branches: [ devbranch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        branches: [newbranch,branch-3,branch-4,branch-5,branch-6,branch-7,branch-8,branch-9,branch-10,branch-11,branch-12,branch-13,branch-14,branch-15,branch-16,branch-17,branch-18,branch-19,branch-20,branch-21,branch-22,branch-23]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setting credentials
    - name: Set Credentials
      run: |
         git config --global user.email "woodsba@insercorp.com"
         git config --global user.name "Benjamin Woods"
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git fetch origin --unshallow
        git checkout ${{ matrix.branches }}
        git pull origin ${{ matrix.branches }}
        git pull origin master
        git push origin ${{ matrix.branches }}
